spring.application.name=document
logging.level.com.example.document=INFO
spring.datasource.url=jdbc:mysql://localhost:3306/collab_space
spring.datasource.username=orcl1
spring.datasource.password=orcl
spring.jpa.hibernate.ddl-auto=update